services:
  mysql:
    container_name: mysql-sql-bsn
    image: mysql
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: book_social_network
    volumes:
      - mysql:/var/lib/mysql/data
    ports:
      - "3308:3306"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

    networks:
      - spring-demo
  bsn-api:
    container_name: bsn-api
    image: bsn/bsn:1.0.3
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - mysql
networks:
  spring-demo:
    driver: bridge

volumes:
  mysql:
    driver: local

